
version: "3.8"
services:
  app:
    build: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/workspace

  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace

  db:
    image: postgres:11.7
    container_name: sample-db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: "todo_user"
      POSTGRES_PASSWORD: "todo_pass"
      POSTGRES_DB: "todo"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432    
    volumes:
      - db-store:/var/lib/postgresql/data

volumes:
  db-store: